name: Create Search Index, then Build and deploy Jekyll site

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    name: CreateBuild and Deploy Jekyll Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      # - name: Install Jekyll
      #   run: |
      #     sudo gem install bundler jekyll
      #     sudo bundle install
      # - name: Delete _site if it exists
      #   run: |
      #     if [ -d "_site" ]; then
      #       rm -rf _site/*
      #     fi
      - name: Build the search index
        uses: tameney22/search-index-action@master
        id: index
        with:
          xml-list: 'b.xml br.xml p.xml t.xml'
          xml-directory: './editions'
          index-directory:  './assets/js/search'
      # - name: Build site
      #   run: bundle exec jekyll build
      # - name: Commit newly built files
      #   run: | 
      #     git config --local user.email "${{ secrets.GIT_EMAIL }}"
      #     git config --local user.name "tameney22"
      #     git add .
      #     git commit -m "Workflow job: Create search index and build"
      #     git push
      # - uses: helaili/jekyll-action@master
      #   env:
      #     JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
      - name: Build and deploy the site to './docs' on the master branch
        uses: victoriadrake/jekyll-cd@master